v1.4.7 エラーレスポンスが復号化されていないのを修正
pokepay/pokepay-partner-node-sdk pull request #11
Opened 2023-11-20 07:59 UTC by masatoi

slack: https://coilinc.slack.com/archives/C8RSWHFHQ/p1700460503162199

topup.js
```js
const ppsdk = require("/home/wiz/pokepay-partner-node-sdk");

async function main() {
  const client = new ppsdk.Client("/home/wiz/tmp/papi-node-test/config.ini");

  const request = new ppsdk.CreateTopupTransaction({
    shop_id: "d2b0cd97-6237-4037-b91e-3a2b102330fc",
    customer_id: "874a1720-c067-4810-b007-1d1a0c1b0578",
    private_money_id: "34abc102-df7f-4d77-840b-ae574168fbeb", // not exist money
    money_amount: 100,
    point_amount: 0
  });

  try{
    const response = await client.send(request);
  } catch (error) {
    console.log(error.response.data);
  }
}

main()
```

before
```
$ node topup.js 
{
  response_data: '7lVWJchM_TE4nlaIjH-bcGy92GeFALaIzYLrXya2seFjfPphGpYpfzOBmM2DnY_rN8HVL6MSy-b-R6V4OiXk0yv_g0LRpS5q0yUGUWNQTOXunQh9pqfTjrHjIJYBVm1C',
  timestamp: '2023-11-20T07:58:24.726Z',
  partner_call_id: '5ccf7a98-28b4-450c-873b-ce1efe989be3'
}
```
after
```
$ node topup.js 
{ type: 'private_money_not_found', message: 'Private money not found' }
```

2023-11-20 08:45 UTC, tsasao requested changes

2023-11-20 08:45 UTC, tsasao commented on dist/client.js
> +            if (axios_1.default.isAxiosError(error) && error.response && error.response.data.response_data) {
error.responseはAxiosResponseなわけだけど、gwとかから非jsonのエラーとかが帰ってくることは普通にあってerror.response.dataはtextだったりhtmlだったりするのでは？

2023-11-20 08:58 UTC, masatoi commented on dist/client.js
> +            if (axios_1.default.isAxiosError(error) && error.response && error.response.data.response_data) {
レスポンスヘッダーでjsonかどうか見るようにしました

2023-11-20 09:33 UTC, tsasao commented on dist/client.js
> +            if (axios_1.default.isAxiosError(error) && error.response && error.response.data.response_data) {
application/json; charset=UTF-8とかにもなり得るし、ヘッダはjsonなのに途中でちょんぎれたものが帰ってきて（どうなるんだろう？）とか、心配もあるので、
単にtypeof error.response.data == "object"でいい気がします。
nullと[]も"object"になりますが、nullは2つ目の判定で偽だし、[]は.参照してもエラーにならないので、大丈夫かなあ、と。
もっといい方法もあるかもしれませんが...

2023-11-21 02:52 UTC, masatoi commented on dist/client.js
> +            if (axios_1.default.isAxiosError(error) && error.response && error.response.data.response_data) {
@tsasao 修正しました

2023-11-21 03:00 UTC, tsasao approved these changes
LGTM.

2023-11-21 03:04 UTC, merged